/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fileoperations;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bthnd
 */
public class giderGor extends javax.swing.JFrame {

    /**
     * Creates new form giderGor
     */
    public giderGor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        toplam = new javax.swing.JLabel();
        kira = new javax.swing.JLabel();
        elektrik = new javax.swing.JLabel();
        su = new javax.swing.JLabel();
        personel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tarihText = new javax.swing.JTextField();
        onayBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gider Gör");

        toplam.setText("Toplam : ");

        kira.setText("Kira :");

        elektrik.setText("Elektrik : ");

        su.setText("Su :");

        personel.setText("Personel : ");

        jLabel7.setText("Tarih");

        tarihText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihTextActionPerformed(evt);
            }
        });

        onayBtn.setText("ONAY");
        onayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(toplam))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kira))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(elektrik))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(su))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarihText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onayBtn)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tarihText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onayBtn))
                .addGap(21, 21, 21)
                .addComponent(toplam)
                .addGap(18, 18, 18)
                .addComponent(kira)
                .addGap(18, 18, 18)
                .addComponent(elektrik)
                .addGap(18, 18, 18)
                .addComponent(su)
                .addGap(18, 18, 18)
                .addComponent(personel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarihTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihTextActionPerformed

    private void onayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onayBtnActionPerformed
        File f = new File(tarihText.getText());

        try {

            BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(f)));
            int devam = 1;
            while (devam != 0) {
                String satir = reader.readLine();
                switch (satir) {
                    case "Kira":
                        String kiraSonuc = reader.readLine();
                        kira.setText("Kira : " + kiraSonuc);
                        break;

                    case "Elektrik":
                        String elektrikSonuc = reader.readLine();
                        elektrik.setText("Elektrik : " + elektrikSonuc);
                        break;

                    case "Su Gideri":
                        String suSonuc = reader.readLine();
                        su.setText("Su : " + suSonuc);
                        break;

                    case "Personel Gideri":
                        String personelSonuc = reader.readLine();
                        personel.setText("Personel : " + personelSonuc);
                        break;

                    case "Toplam":
                        String toplamSonuc = reader.readLine();
                        toplam.setText("Toplam : " + toplamSonuc);
                        break;
                        
                    case "":
                        devam = 0;

                    default:
                        devam = 0;
                        break;

                }
            }

        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {
            Logger.getLogger(giderGor.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_onayBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giderGor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giderGor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giderGor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giderGor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giderGor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel elektrik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel kira;
    private javax.swing.JButton onayBtn;
    private javax.swing.JLabel personel;
    private javax.swing.JLabel su;
    private javax.swing.JTextField tarihText;
    private javax.swing.JLabel toplam;
    // End of variables declaration//GEN-END:variables
}
